

#define CONST_NUMBOFCOINPERBLOCK              	1000
#define CONST_SECPERBLOCK			90	
#define CONST_READJUSTPERIOD			.5*24*60*60

#define CONST_MAXNUMBCOINS			1000000000
#define CONST_MAXNUMBEROFBLOCKPERDAY
#define CONST_PUBKEYADDRESS
#define CONST_INITEPOCTIME
#define CONST_EPOCTIMEVERBIAGE
#define CONST_NULLKERKLEHASH
#define CONST_MERKLEHASH
#define CONST_DOGENESISBLOCK
#define CONST_GENESISBLOCKHASH
#define CONST_GENESISBLOCKNOUNCE

